### ISSUE TITLE
Unable to display Pi-hole admin

### ISSUE THREAD

**Issue by suryjuto** [mescon/Muximux#101]
Just setup Pi-hole running on an Ubuntu container.  Nothing displays when adding to my Muximux panel.

**Comment by mescon** [comment]
I'm gonna close this issue because you are not telling us anything that would help debug the issue.

Maybe this is of some value to you - I don't know: https://github.com/mescon/Muximux/issues/74

**Comment by mmolitor87** [comment]
This is due to X-Frame Headers that prevent it from being included in a frame. For Chrome I use the addon 'Ignore X-Frame Headers' and it works great.

**Comment by rpluto** [comment]
About this issue, i comment this code 

$HTTP["url"] =~ "^/admin/" {
    # Create a response header for debugging using curl -I
#    setenv.add-response-header = (
#        "X-Pi-hole" => "The Pi-hole Web interface is working!",
#        "X-Frame-Options" => "DENY"
#    )

    $HTTP["url"] =~ "\.(eot|otf|tt[cf]|woff2?)$" {
        # Allow Block Page access to local fonts
        setenv.add-response-header = ( "Access-Control-Allow-Origin" => "*" )
    }
}

under lighttpd.conf.debian 
https://github.com/pi-hole/pi-hole/blob/master/advanced/lighttpd.conf.debian

and mount somewhere from you configuration under pihole docker 

...
 volumes:
- ./pihole/pihole-conf/etc/lighttpd/lighttpd.conf.debian:/etc/.pihole/advanced/lighttpd.conf.debian

....

because its copy on every reboot.
