### ISSUE TITLE
pfsense loads but removes tab frame

### ISSUE THREAD

**Issue by nullredvector** [mescon/Muximux#156]
I have other https apps running just fine using the chrome extension mentioned in the README. pfsense is unique that when clicking on the pfsense tab in muximux, the page loads but then removes the tab frame and loads the pfsense url in the address bar - essentially the tab acts as a link. Using the back button results in being redirected back to pfsense.

**Comment by mescon** [comment]
I have no way to verify because I don't have pfSense but that sounds to me like pfSense uses a frame breakout script such as https://en.wikipedia.org/wiki/Framekiller

At the same time, the ``sanbox`` options on the iframes should disallow it from accessing the top level DOM. Can you verify what pfSense is doing?

**Comment by nullredvector** [comment]
Thank you!

I followed that through google and their forums and it led me to:
1. https://forum.pfsense.org/index.php?topic=47167.msg248336#msg248336
2. then check this box:
Browser HTTP_REFERER enforcement - Disable HTTP_REFERER enforcement check

Now pfsense works in muximux :D

**Comment by d8ahazard** [comment]
Instructions added to readme with 66b11488206b44364b6ed8bb438462cbbb0835c5.
