### ISSUE TITLE
try private IP before public domain

### ISSUE THREAD

**Issue by aporzio1** [mescon/Muximux#160]
is there a way to have it try a local IP i.e. 192.168.x.x before trying my domain name. 

Example:
If I am home it would access the site by 192.168.x.x and if I am anywhere else it will go through my domain name

**Comment by kube1984** [comment]
if your trying to do this on a local computer at home....add a host entry to redirect the url to local ip as that always takes presence before using DNS

**Comment by aporzio1** [comment]
I could. but it would have to be done on every computer, and there is no solution for phone or tablet

**Comment by mescon** [comment]
I think this is already possible since this patch: https://github.com/mescon/Muximux/commit/b2d38ac9ae0b5dc2181fa14479c906b2139e66d7

Basically, try entering something like ``https://:443/sonarr`` which should become ``https://192.168.x.x:443/sonarr`` if you're visiting the site at 192.168.x.x.
If you instead type somehost.com into your url to open up Muximux, the URL should become ``https://somehost.com:443/sonarr``.

Don't know if it works - I don't use that function myself.

If you control your own DNS server, the technique to serve different answers to DNS requests depending on where they come from (i.e your internal network, or the external network) is known as Split-horizon DNS https://en.wikipedia.org/wiki/Split-horizon_DNS
