### ISSUE TITLE
Error: Failed to read the 'localStorage' property

### ISSUE THREAD

**Issue by lukezona** [mescon/Muximux#186]
Lot of my websites can't load because they aren't allowed to check for tokens saved in localStorage.
For example Ombi, Netdata and MyJDownloader can't be loaded.

Errors are like this:
> Uncaught (in promise) DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at tokenGetter

I've tried in Incognito mode as well but the problem persist.

Any idea?

**Comment by mescon** [comment]
That's because of this probably:
https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

https://stackoverflow.com/questions/30481516/iframe-in-chrome-error-failted-to-read-localstorage-from-window-access-den

Let me know if this fixes it. Muximux itself can't do anything about your settings - it simply embeds sites as iframes, which is what you're blocking :)

**Comment by lukezona** [comment]
Yes, I've added my url to Chrome's whitelist and it fixes the problem for almost every website.

Now only one is still not loading with this error:

> com.google.gwt.core.client.JavaScriptException: (SecurityError) : Failed to execute 'assign' on 'Location': The current window does not have permission to navigate the target frame to 'https://my.jdownloader.org/index.html?deviceId={myID}#webinterface:downloads'.

There's a way to fix it?
