### ISSUE TITLE
[Feature Request] Landing Page with large icons for each service

### ISSUE THREAD

**Issue by some-guy-23** [mescon/Muximux#39]
It would be nice to have an option where instead of loading the first app, you could instead arrive at a page that shows large icons for each service.

This could be done by a javascript check to see if the page has just loaded (before any service is clicked). A class could be added to the body of the HTML, which then allows you to display the top nav menu in a larger style.

**Comment by d8ahazard** [comment]
This is on my radar, along with the other stuff in the issues list.  ;)

**Comment by d8ahazard** [comment]
This feature has been implemented into the Development branch and will be pushed to Master once I've tested all the use-cases and made sure there are no bugs.  The current implementation is sufficient for me to mark this as closed.

![image](https://cloud.githubusercontent.com/assets/1633844/21285026/d3686d9e-c3f2-11e6-8f6b-bdecef103c6e.png)

![image](https://cloud.githubusercontent.com/assets/1633844/21285032/ee2f2ec4-c3f2-11e6-805d-4295384350de.png)

**Comment by NowayIndustries** [comment]
I love the icons d8ahazard I think it is an amazing addition to Muximux.

One small problem (yes I am on the develop branch but still): combineify.php takes a long time to complete it's initial run, I had to up 'max_execution_time = 300;' in my php.ini and 'max_execution_time = 300;' in my nginx php config. 
Granted it is being run on a Raspberry Pi so it should not be a 'real' issue but I figured that writing down the solution prevents someone else from pulling their hair out. 
(I needed both settings because first PHPFPM would give it's error about the 30 second max execution time and then I would get an Nginx error about the upstream (phpfpm) not responding.)

**Comment by NowayIndustries** [comment]
Another day another bug/issue:
If you enable the landing page for a site you've added to Muximux it will load in a second copy of Muximux in the tab instead of the landing page. The second copy will show the splash screen if enabled, otherwise it will just show the default page.
To reproduce:

1. Set one of the sites to have a landing page.
2. Click on the tab to open the site with the landing page enabled.
3. Muximux will load again, inside the tab's iframe.
![Nested muximux](http://i.imgur.com/UhMplvD.png)
In the image: owncloud is set to have a landing page, duckduckgo is the default page. Refreshing the page will remove the nested muximux, until you visit the tab with the landing page again.

**Comment by d8ahazard** [comment]
@NowayIndustries - Both issues should be fixed - I was missing the handler for the landingpage PHP call, and I added an ini set to up the max_execution_time before Combineify is called.

Thanks for reporting these.  In the future, if you find an issue, please report it directly in the issue tracker so we can address them individually.  :D
