### ISSUE TITLE
Folder In Navbar

### ISSUE THREAD

**Issue by dcplaya** [mescon/Muximux#4]
Id like to use this as my new landing page to replace my reverse proxy I currently have. It would be nice to have "folders" so I could put admin stuff such as my FreeNAS page and Proxmox page in it. 

It would be really nice to integrate this with the users request. Hide entire folders or just parts of the folder.

**Comment by mescon** [comment]
You would still need a reverse proxy - Muximux itself does not act as a proxy to internal stuff. If Proxmox/CouchPotato/whatever is not reachable from the outside, Muximux won't do it for you.

**Comment by dcplaya** [comment]
My idea would be to run my reverse proxy to point to Muximux. Muximux would be internal and have access to everything I host internally.

**Comment by mescon** [comment]
That wouldn't work anyway. Muximux does not channel anything through it - it only links to other things.
All services must be accessible from the place you're accessing Muximux from.

I've got a version of the folder-thing working btw, haven't pushed it to repo yet because I'm not happy with the design of it yet.
