### ISSUE TITLE
Unable to open secret.txt

### ISSUE THREAD

**Issue by kylerw** [mescon/Muximux#41]
![image](https://cloud.githubusercontent.com/assets/370860/12765549/5e0295ba-c9bc-11e5-9faf-3c6113e9188a.png)

**Comment by kylerw** [comment]
Permissions on the secret.txt file are not correct. Manually fixing it resolved on my end.

**Comment by SyNiK4L** [comment]
Interesting. You mean they were not correct on download? I've never had this problem installing fresh.

**Comment by kylerw** [comment]
Correct, on update.

**Comment by mescon** [comment]
I think this is because any new files you get from doing ``git pull`` are set with the permissions of the user you are doing the git command as - while the PHP code is trying to write to the file as the user your webserver is running as.
I don't think we can control this, so we might have to add a line or two about this to guide people who perhaps are not as smart as you @kylerw :-)
