### ISSUE TITLE
Not able to add Emby

### ISSUE THREAD

**Issue by WebBuddha** [mescon/Muximux#44]
I'm not able to add Emby https://emby.media/ to Muximux which is running an my Synology Storage.
I've edited `/volume1/@appstore/emby/var/config/system.xml` and changed line `<DenyIFrameEmbedding>true</DenyIFrameEmbedding>` to `<DenyIFrameEmbedding>false</DenyIFrameEmbedding>` and did a restart of emby.
Anyone here who implemeted it correctly?

**Comment by mescon** [comment]
I really have no clue why this wouldn't work, given that the ``/volume1/@appstore/emby/var/config/system.xml`` file is the config that Emby is actually using when you start it.

As long as the application is not sending ``X-Frame-Options: Deny`` your browser has no problem with framing the content.

The only other plausible reason I can think of is if you are running Muximux from a HTTPS-enabled webserver, while your Emby installation is NOT secured with HTTPS.
If so, try either by running Muximux in a non-HTTPS enabled webserver, or enable HTTPS on Muximux and point it to https://whatever.blabla.com/emby (note the https in the beginning).

You could also try the Chrome/Opera/Chromium plugin described here: https://github.com/mescon/Muximux#important-note-regarding-https

**Comment by hypyke** [comment]
This is still a problem - Emby is sending   `X-Frame-Options: SAMEORIGIN`

It's not an HTTPS issue for me because emby is not running https

**Comment by mescon** [comment]
And both Muximux and Emby are called from the same domain? (example.hypyke.com for instance) And Muximux is not served via HTTPS? (if Muximux is on HTTPS and Emby is NOT, then you need to either secure Muximux or you need to serve Muximux via HTTP instead).

**Comment by hypyke** [comment]
No.  I only use Muximux and Emby internally and the hosts are 192.168.100.24 and 192.168.100.25 for example.  HTTPS isn't use on Emby or Muximux.  It does seem to be the frame issue because I installed
https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe

> Ignore X-Frame headers 

in chrome as a workaround and now it works.  So it's fine for me but wouldn't b for a lot of people.  Not sure why emby sends that header and not sure there is much you can do about it.  Perhaps id the landing page launched the site in a new tab instead of in the frame?

**Comment by mescon** [comment]
Thats because you are running it on two separate hosts as well. If the header is SAME-DOMAIN, they need to be on the same domain name or on the same IP of no domain exists.

**Comment by 2devnull** [comment]
this sucks, not even same domain works....and the chorme plugin doesn't even have a per-site option, i.e. all on, all off.
