### ISSUE TITLE
Deluge not accepting password.

### ISSUE THREAD

**Issue by sparklyballs** [mescon/Muximux#45]
Hi there, trying to develop a docker container for this app and am hitting an issue with deluge not accepting password.

If i enter an incorrect password it acknowledges the password is incorrect, if i enter the correct password the password box empties and the app doesn't redirect to the deluge page.

Could you take a look here and see if we are missing anything obvious.

https://github.com/linuxserver/docker-muximux

thanks.

**Comment by mescon** [comment]
Though this is not a Muximux problem, I'll let you know about a problem I had, that might help you out anyways.
I had the same symptoms, and it turned out that is was my nginx reverse proxy that didn't set the correct headers, that Deluge needs when it is acting behind a reverse proxy.

My working setup looks like this:
```
location /deluge {
        proxy_pass  http://127.0.0.1:8112/;
        proxy_redirect  off;
        proxy_set_header  Host       $host;
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass_header Set-Cookie;
        proxy_pass_header P3P;

}

```
