### ISSUE TITLE
[Feature request] Add option in landing page to open link in new tab

### ISSUE THREAD

**Issue by maxime-roy** [mescon/Muximux#47]
Hi!

I've just started to use Muximux and it's awesome!

However, I have a small issue with it. When I use Muximux to open an application that already uses multiple iframes (in this case Subsonic), all the javascripts used to do interactions with the application aren't working. When I open the same application but without Muximux, everything is working properly. 

In order to bypass this issue but still have the application listed in Muximux, I think it could be great to add an option in landing page to open link in new tab. I know that we could just right-click on the "launch x app" button and then click on open in new tab but it could be convenient don't you think?

If you need more clarification don't hesitate to let me know!

Kind regards,

**Comment by mescon** [comment]
Hi @maxime-roy.
Though I appreciate your well written feature request, I don't agree with implementing this inside of Muximux itself, basically because I see this as redundant. You're free to bookmark applications directly, and right now I do not have plans to implement this feature.

Things might change if I happen to be up some night having nothing better to do, but until then I'm closing this issue.

I'd be happy to review a pull request if somebody wants to implement this though.

**Comment by Siebes** [comment]
As a work around for the lazy do this
`http://urlhere.com" target="_blank" title="Title you want"><br "`

**Comment by jedimstr** [comment]
@Siebes - the work around doesn't seem to work. The escape \ get's dropped on save.

**Comment by Siebes** [comment]
@jedimstr try editing the settings.ini.php file directly - this is just a hack

**Comment by crpgbogor** [comment]
I've tried it but the workaround doesn't work. I need it because ubooquity refuse to download pdf when used inside muximux. Probably because of my chrome setting which choose to view pdf instead of downloading it.
