### ISSUE TITLE
Is it possible to run muximux through a reverse proxy with https and serve http pages?

### ISSUE THREAD

**Issue by 10481** [mescon/Muximux#60]
The reason I ask is that I've spent more time than I should have trying to get that setup to work, but I guess it falls under the same principle as just serving muximux via https directly. I run sonarr via arch linux and it's becoming apparent that SSL doesn't work for it, so I was hoping I could use a reverse proxy in a similar fashion that I have now where I serve standard http via reverse proxy https.

**Comment by mescon** [comment]
What do you mean with running Muximux "through a reverse proxy"? Behind a reverse proxy? Before a reverse proxy? ON the reverse proxy server?

I have sonarr running internally on 192.168.1.2:8989 (http)... but when I connect to nginx on https://my.domain.com/sonarr it gets the data from Sonarr internally - as far as the browser is concerned, everything is HTTPS because it only talks with the reverse proxy (nginx).

Muximux has nothing to do with that.
